In [1]:
import pandas as pd

In [2]:


data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [20, 25, 22, 23, 21],
    "Marks": [50, 80, 75, 90, 60]
}

df = pd.DataFrame(data)

# TASK:
# 1. Marks > 70 wale students
# 2. Age < 23 AND Marks > 60
# 3. Sirf Name aur Marks print karo jaha Marks > 75
# 4. Marks 60–80 ke beech wale

In [3]:
print(df[df["Marks"] > 70])
filtered = df[(df["Marks"] > 60 ) & (df["Age"] <23)]
print(filtered)
print(df[df["Marks"] > 75][["Name" ,"Marks"]])
print(df[df["Marks"].between(60,80)])

  Name  Age  Marks
1    B   25     80
2    C   22     75
3    D   23     90
  Name  Age  Marks
2    C   22     75
  Name  Marks
1    B     80
3    D     90
  Name  Age  Marks
1    B   25     80
2    C   22     75
4    E   21     60

In [4]:


data = {
    "Name": ["A", "B", "C", "D", "E", "F", "G"],
    "Age": [20, 25, 22, 23, 21, 24, 26],
    "Marks": [50, 80, 75, 90, 60, 55, 85],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai", "Delhi", "Pune"]
}

df = pd.DataFrame(data)

In [5]:
#  Q 1 : Marks > 70
mask = df["Marks"] > 70
filtered = df[mask]
print(filtered)
print("Count : ", len(filtered))

  Name  Age  Marks    City
1    B   25     80  Mumbai
2    C   22     75   Delhi
3    D   23     90    Pune
6    G   26     85    Pune
Count :  4

In [6]:
#  Q2. Age < 23 And Marks > 60
msk = (df["Marks"] > 60) & (df["Age"] < 23)
flt = df[msk]
print(flt)
print("Count : ", len(flt))

  Name  Age  Marks   City
2    C   22     75  Delhi
Count :  1

In [7]:
#  Q3. Marks <60 OR Age > 24
msk = (df["Marks"] < 60) | (df["Age"] > 24)
flt = df[msk]
print(flt)
print("Count : ", len(flt))

  Name  Age  Marks    City
0    A   20     50   Delhi
1    B   25     80  Mumbai
5    F   24     55   Delhi
6    G   26     85    Pune
Count :  4

In [8]:
# Q4: Sirf Name aur Marks jaha Marks > 75
print(df[(df["Marks"] > 75)][["Name", "Marks"]])

  Name  Marks
1    B     80
3    D     90
6    G     85

In [9]:
# Q5. Marks between 60 and 85
print(df[df["Marks"].between(60,85)])

  Name  Age  Marks    City
1    B   25     80  Mumbai
2    C   22     75   Delhi
4    E   21     60  Mumbai
6    G   26     85    Pune

In [10]:
# Q6: City = "Delhi"
mask = df["City"] == "Delhi"
filterd = df[mask]
print(filterd)
print("Count : ",len(filterd))

  Name  Age  Marks   City
0    A   20     50  Delhi
2    C   22     75  Delhi
5    F   24     55  Delhi
Count :  3

In [11]:
# Q7: City = Delhi AND Marks > 70
print(df[(df["City"] == "Delhi") & (df["Marks"] > 70)])

  Name  Age  Marks   City
2    C   22     75  Delhi

In [12]:
# Q8: Names ["A", "D", "G"] select karo
filtered = df[df["Name"].isin(["A","D","G"])]
print(filtered)

  Name  Age  Marks   City
0    A   20     50  Delhi
3    D   23     90   Pune
6    G   26     85   Pune

In [13]:
# Q9: Count students jinke Marks > 70
new = df["Marks"] > 70
count = df[new]
print("Count : ",len(count))

Count :  4

In [14]:
# Q10: Marks < 60 walon ko 0 replace karo
df.loc[df["Marks"] < 60, "Marks"] = 0

print(df)

  Name  Age  Marks    City
0    A   20      0   Delhi
1    B   25     80  Mumbai
2    C   22     75   Delhi
3    D   23     90    Pune
4    E   21     60  Mumbai
5    F   24      0   Delhi
6    G   26     85    Pune

In [15]:
# Q11: Age 21 se 25 ke beech + Marks > 60
print(df[(df["Age"].between(21,25)) & (df["Marks"] > 60)])

  Name  Age  Marks    City
1    B   25     80  Mumbai
2    C   22     75   Delhi
3    D   23     90    Pune

In [16]:
# Q12: City Mumbai wale + sirf Name, Marks
print(df[df["City"] == "Mumbai"][["Name" , "Marks"]])

  Name  Marks
1    B     80
4    E     60

In [17]:
# Q13: NOT condition (Marks <= 70)
mask = ~(df["Marks"] <= 70)
result = df[mask]

print(result)

  Name  Age  Marks    City
1    B   25     80  Mumbai
2    C   22     75   Delhi
3    D   23     90    Pune
6    G   26     85    Pune

In [18]:
# Q14: Marks > 60 ke baad descending sort
filtered = df[df["Marks"] > 60]

result = filtered.sort_values(by="Marks", ascending=False)

print(result)

  Name  Age  Marks    City
3    D   23     90    Pune
6    G   26     85    Pune
1    B   25     80  Mumbai
2    C   22     75   Delhi

In [19]:
# Q15: Top 3 highest marks wale students
top3 = df.sort_values(by="Marks", ascending=False).head(3)

print(top3)

  Name  Age  Marks    City
3    D   23     90    Pune
6    G   26     85    Pune
1    B   25     80  Mumbai

In [20]:
# Q1: City = Delhi ya Chennai
# Q2: Name = ["A","C"]
# Q3: NOT → Delhi aur Mumbai hatao
df

  Name  Age  Marks    City
0    A   20      0   Delhi
1    B   25     80  Mumbai
2    C   22     75   Delhi
3    D   23     90    Pune
4    E   21     60  Mumbai
5    F   24      0   Delhi
6    G   26     85    Pune

In [21]:
df = pd.DataFrame({
    "Name": ["A","B","C","D","E"],
    "City": ["Delhi","Mumbai","Pune","Delhi","Chennai"]
})

In [22]:
# Q1: City = Delhi ya Chennai
result = df[df["City"].isin(["Delhi" , "Chennai"])]
print(result)

  Name     City
0    A    Delhi
3    D    Delhi
4    E  Chennai

In [23]:
# Q2: Name = ["A","C"]
resu = df[df["Name"].isin(["A","C"])]
print(resu)

  Name   City
0    A  Delhi
2    C   Pune

In [24]:
# Q3: NOT → Delhi aur Mumbai hatao
result = df[~df["City"].isin(["Delhi" , "Mumbai"])]
print(result)

  Name     City
2    C     Pune
4    E  Chennai

In [27]:
#  Sort values 
# 3 questions

data = {
    "Name": ["A", "B", "C", "D", "E", "F", "G"],
    "Age": [20, 25, 22, 23, 21, 24, 26],
    "Marks": [50, 80, 75, 90, 60, 55, 85],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai", "Delhi", "Pune"]
}

df = pd.DataFrame(data)

In [28]:
# Q4: Marks ascending sort
sot = df.sort_values(by= "Marks",ascending= True)
print(sot)

  Name  Age  Marks    City
0    A   20     50   Delhi
5    F   24     55   Delhi
4    E   21     60  Mumbai
2    C   22     75   Delhi
1    B   25     80  Mumbai
6    G   26     85    Pune
3    D   23     90    Pune

In [ ]:
# Q5: Marks descending sort
sot = df.sort_values(by= "Marks",ascending= False)
print(sot)

  Name  Age  Marks    City
3    D   23     90    Pune
6    G   26     85    Pune
1    B   25     80  Mumbai
2    C   22     75   Delhi
4    E   21     60  Mumbai
5    F   24     55   Delhi
0    A   20     50   Delhi

In [29]:
# Q6: City + Marks dono se sort
sot = df.sort_values(by= ["Marks","City"] ,ascending= True)
print(sot)

  Name  Age  Marks    City
0    A   20     50   Delhi
5    F   24     55   Delhi
4    E   21     60  Mumbai
2    C   22     75   Delhi
1    B   25     80  Mumbai
6    G   26     85    Pune
3    D   23     90    Pune

In [ ]:
# head()
df

  Name  Age  Marks    City
0    A   20     50   Delhi
1    B   25     80  Mumbai
2    C   22     75   Delhi
3    D   23     90    Pune
4    E   21     60  Mumbai
5    F   24     55   Delhi
6    G   26     85    Pune

In [30]:
# Q7: Top 2 rows
df.head(2)

  Name  Age  Marks    City
0    A   20     50   Delhi
1    B   25     80  Mumbai

In [31]:
# Q8: Marks sort → top 2
sot = df.sort_values(by= "Marks" ,ascending= True).head(2)
print(sot)

  Name  Age  Marks   City
0    A   20     50  Delhi
5    F   24     55  Delhi

In [32]:
# Q9: Delhi filter → sort → top 2
result = df[df["City"] =="Mumbai"] \
            .sort_values(by = "Marks" ,ascending = False) \
            .head(2)

print("Final Result : \n ",result)

Final Result :
    Name  Age  Marks    City
1    B   25     80  Mumbai
4    E   21     60  Mumbai

loc function

In [76]:
df = pd.DataFrame({
    "Name": ["A","B","C","D","E"],
    "Marks": [80, 50, 90, 40, 70],
    "City": ["Delhi","Mumbai","Delhi","Pune","Delhi"]
})
df

  Name  Marks    City
0    A     80   Delhi
1    B     50  Mumbai
2    C     90   Delhi
3    D     40    Pune
4    E     70   Delhi

In [34]:
# Marks < 50 → -1 replace
df.loc[df["Marks"] < 50 , "Marks"] = -1
print(df)

  Name  Marks    City
0    A     80   Delhi
1    B     50  Mumbai
2    C     90   Delhi
3    D     -1    Pune
4    E     70   Delhi

In [35]:
# Sirf Name aur City column print karo
print(df[["Name" , "City"]])

  Name    City
0    A   Delhi
1    B  Mumbai
2    C   Delhi
3    D    Pune
4    E   Delhi

In [36]:
# Pune wale students filter karo
# sirf Name print karo
sort = df[df["City"] == "Pune"]
print(sort["Name"])

3    D
Name: Name, dtype: str

In [46]:
# Marks > 70 walon ka City = "Topper" kar do

sot = df[df["Marks"] > 70]  
sot["City"] = "Topper"
sot

  Name  Marks    City
0    A     80  Topper
2    C     90  Topper

In [57]:
# Delhi students filter karo
# sirf Name aur Marks dikhao
df
sot = df[df["City"] == "Delhi"][["Marks","Name"]]
print(sot)

   Marks Name
0     80    A
2     90    C
4     70    E

In [61]:
# Marks ascending sort karo
# top 3 students dikhao
print(df.sort_values(by ="Marks" , ascending= True ).head())

  Name  Marks    City
3    D     40    Pune
1    B     50  Mumbai
4    E     70   Delhi
0    A     80   Delhi
2    C     90   Delhi

In [ ]:
# Marks < 60 walon ko 0 karo
# phir Delhi students filter karo
# sirf Name aur Marks dikhao
df.loc[df["Marks"] <60 , "Marks"] = 0
df[df["City"] == "Delhi"][["Name","Marks"]]

  Name  Marks    City
0    A     80   Delhi
1    B     50  Mumbai
2    C     90   Delhi
3    D     40    Pune
4    E     70   Delhi

In [71]:
df

  Name  Marks    City
0    A     80   Delhi
1    B     50  Mumbai
2    C     90   Delhi
3    D     40    Pune
4    E     70   Delhi

In [74]:
df.loc[df["Marks"] > 70 , "City"] = "High"
df.sort_values(by = "Marks" , ascending= False).head(2)

  Name  Marks  City
2    C     90  High
0    A     80  High

In [78]:
df

  Name  Marks    City
0    A     80   Delhi
1    B     50  Mumbai
2    C     90   Delhi
3    D     40    Pune
4    E     70   Delhi

In [ ]:
# Pune aur Mumbai students hatao
# Marks > 60 filter
# descending sort
# top 3
# sirf Name, Marks

In [ ]:
# Pune aur Mumbai students hatao
sot = df[df["Marks"] > 60]
print(sot)

  Name  Marks   City
0    A     80  Delhi
2    C     90  Delhi
4    E     70  Delhi

In [83]:
# Marks > 60 filter
result = result = df[~df["City"].isin(["Pune", "Mumbai"])] \
        [df["Marks"] > 60]\
        .sort_values(by= "Marks",ascending= False)\
        .head(3)[["Name","Marks"]]
print(result)

  Name  Marks
2    C     90
0    A     80
4    E     70

C:\Users\MAINAK\AppData\Local\Temp\ipykernel_10068\2845918060.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = result = df[~df["City"].isin(["Pune", "Mumbai"])] \