In [1]:
import pandas as pd

In [2]:
import matplotlib as plt

## Creating Data Frame ##

In [3]:
# using lists

student_data = [
    [100,80,10],
    [90,70,8.8],
    [120,100,14],
    [180,100,20]
]
pd.DataFrame(student_data,columns=['Iq','marks','package'])

    Iq  marks  package
0  100     80     10.0
1   90     70      8.8
2  120    100     14.0
3  180    100     20.0

In [4]:
# using dicts

student_data = {
   'iq': [100,80,10],
    'marks' :[90,70,8.8],
    'packages' :[120,100,14],\

}
students = pd.DataFrame(student_data)
students

    iq  marks  packages
0  100   90.0       120
1   80   70.0       100
2   10    8.8        14

In [5]:
# using read.csv
movies = pd.read_csv(r'C:\Users\MAINAK\Desktop\SQl\ds\Python_Pandas\movies.csv')
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [6]:
ipl = pd.read_csv(r'C:\Users\MAINAK\Desktop\SQl\ds\Python_Pandas\ipl-matches.csv')
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

# DataFrame Attributes and Methods

In [7]:
# shape
movies.shape

(1629, 18)

In [8]:
# dtypes
movies.dtypes

title_x                 str
imdb_id                 str
poster_path             str
wiki_link               str
title_y                 str
original_title          str
is_adult              int64
year_of_release       int64
runtime                 str
genres                  str
imdb_rating         float64
imdb_votes            int64
story                   str
summary                 str
tagline                 str
actors                  str
wins_nominations        str
release_date            str
dtype: object

In [9]:
# index
movies.index

RangeIndex(start=0, stop=1629, step=1)

In [10]:
# columns
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='str')

In [11]:
# values 
students.values
movies.values

array([['Uri: The Surgical Strike', 'tt8291224',
        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg',
        ...,
        'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|',
        '4 wins', '11 January 2019 (USA)'],
       ['Battalion 609', 'tt9472208', nan, ...,
        'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|',
        nan, '11 January 2019 (India)'],
       ['The Accidental Prime Minister (film)', 'tt6986710',
        'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg',
        ...,
        'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|',
        nan, '11 January 2019 (USA)'],
       ...,
       ['Sabse Bada Sukh', 'tt0069204', nan, ...,
        'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|',
        nan, nan],
       ['Daaka', 'tt10833860',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg',
        ..., 'Gippy Grewal|Zareen Khan|', nan, '1 November 2019 (USA)'],
       ['Humsafar', 'tt2403201',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
        ..., 'Fawad Khan|', nan, 'TV Series (2011–2012)']],
      shape=(1629, 18), dtype=object)

In [12]:
# head and tail
movies.head(2)
ipl.tail(4)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [13]:
# sample
movies.sample(7
)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1429,Footpath (2003 film),tt0374660,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Footpath_(2003_f...,Footpath,Footpath,0,2003,164,Action|Crime|Drama,5.3,712,Poor Arjun is friendly with Shekhar and Raghu ...,Two friends of a man help him avenge his fathe...,NaN,Aftab Shivdasani|Bipasha Basu|Rahul Dev|Emraan...,1 win,15 August 2003 (India)
526,Mary Kom (film),tt3001638,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mary_Kom_(film),Mary Kom,Mary Kom,0,2014,122,Action|Biography|Drama,6.8,9307,A chronicle of the life of Indian boxer Mary K...,A chronicle of the life of Indian boxer Mary K...,NaN,Priyanka Chopra|Sunil Thapa|Robin Das|Rajni Ba...,7 wins & 10 nominations,5 September 2014 (India)
686,Life Ki Toh Lag Gayi,tt2327389,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Life_Ki_Toh_Lag_...,Life Ki Toh Lag Gayi,Life Ki Toh Lag Gayi,0,2012,155,Comedy,5.5,233,A one-day journey of four different people str...,A one-day journey of four different people str...,NaN,Kay Kay Menon|Ranvir Shorey|Pradhuman Singh|Ne...,NaN,20 April 2012 (India)
87,Aiyaary,tt6774212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aiyaary,Aiyaary,Aiyaary,0,2018,157,Action|Thriller,5.2,3538,General Gurinder Singh comes with a proposal t...,After finding out about an illegal arms deal ...,The Ultimate Trickery,Sidharth Malhotra|Manoj Bajpayee|Rakul Preet S...,1 nomination,16 February 2018 (USA)
795,Mummy Punjabi,tt2066925,https://upload.wikimedia.org/wikipedia/en/4/45...,https://en.wikipedia.org/wiki/Mummy_Punjabi,Mummy Punjabi: Superman Ki Bhi Maa!!,Mummy Punjabi: Superman Ki Bhi Maa!!,0,2011,121,Comedy|Drama,5.5,31,Chandigarh-based Baby Arora lives a wealthy li...,An eccentric woman's life undergoes many chang...,NaN,Kiron Kher|Kanwaljit Singh|Jackie Shroff|Anju ...,NaN,31 August 2011 (India)
1085,Jahan Jaaeyega Hamen Paaeyega,tt1236470,https://upload.wikimedia.org/wikipedia/en/2/20...,https://en.wikipedia.org/wiki/Jahan_Jaaeyega_H...,Jahan Jaaeyega Hamen Paaeyega,Jahan Jaaeyega Hamen Paaeyega,0,2007,137,Action|Crime|Drama,4.3,29,Karan loves Anju but she gets murdered and K...,Karan loves Anju but she gets murdered and K...,Wherever you go| you will find me !!,Govinda|Divyaa Dwivedi|Razak Khan|Adi Irani|Je...,NaN,6 July 2007 (India)
1238,Chehraa,tt0449870,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chehraa_(2005_film),Chehraa,Chehraa,0,2005,136,Thriller,3.8,112,Reena and fellow collegian Akash Mehta are med...,Reena and fellow collegian Akash Mehta are med...,NaN,Bipasha Basu|Dino Morea|Preeti Jhangiani|Irrfa...,NaN,18 February 2005 (India)

In [14]:
# info
movies.info(5)

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 229.2 KB

In [15]:
# describe
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [16]:
# is null
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [17]:
movies.notnull()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
1,True,True,False,True,True,True,True,True,True,True,True,True,True,True,False,True,False,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,False,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,False,True
4,True,True,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,False,True
1625,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,False,True
1626,True,True,False,True,True,True,True,True,True,True,True,True,True,True,False,True,False,False
1627,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,False,True
1628,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,False,True

In [18]:
# duplicates
movies.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1624    False
1625    False
1626    False
1627    False
1628    False
Length: 1629, dtype: bool

In [19]:
#rename
students.rename(columns={'marks': 'percent','packages':'lpa'})

    iq  percent  lpa
0  100     90.0  120
1   80     70.0  100
2   10      8.8   14

## Math Modules

In [20]:
# sum -> axis argument'
movies.sum()

title_x             Uri: The Surgical StrikeBattalion 609The Accid...
imdb_id             tt8291224tt9472208tt6986710tt8108208tt6028796t...
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y             Uri: The Surgical StrikeBattalion 609The Accid...
original_title      Uri: The Surgical StrikeBattalion 609The Accid...
is_adult                                                            0
year_of_release                                               3274720
runtime             1381311121211029710910414812013415314313014311...
genres              Action|Drama|WarWarBiography|DramaCrime|DramaD...
imdb_rating                                                    9053.1
imdb_votes                                                    8770965
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline             They didn't mean to change the world.Apna Time...
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations    4 wins17 wins & 1 nomination3 wins & 5 nominat...
release_date        11 January 2019 (USA)11 January 2019 (India)11...
dtype: object

In [21]:
# students.sum(axis = 1)

In [22]:
students

    iq  marks  packages
0  100   90.0       120
1   80   70.0       100
2   10    8.8        14

In [23]:
students.mean(axis= 1)

0    103.333333
1     83.333333
2     10.933333
dtype: float64

In [24]:
students.std()

iq          47.258156
marks       42.306186
packages    56.320511
dtype: float64

In [25]:
students.var()

iq          2233.333333
marks       1789.813333
packages    3172.000000
dtype: float64

# Selecting column from a data frame

In [26]:
# single cols
movies['title_x']

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: str

In [27]:
# multiple cols
movies[['title_x','year_of_release','actors']]

,title_x,year_of_release,actors
0,Uri: The Surgical Strike,2019,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1,Battalion 609,2019,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2,The Accidental Prime Minister (film),2019,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3,Why Cheat India,2019,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4,Evening Shadows,2018,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...,...,...,...
1624,Tera Mera Saath Rahen,2001,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625,Yeh Zindagi Ka Safar,2001,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626,Sabse Bada Sukh,2018,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627,Daaka,2019,Gippy Grewal|Zareen Khan|
1628,Humsafar,2011,Fawad Khan|

In [28]:
ipl[['Team1','Team2','WinningTeam','Date']]

,Team1,Team2,WinningTeam,Date
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans,2022-05-29
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,2022-05-27
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore,2022-05-25
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans,2022-05-24
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings,2022-05-22
...,...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders,2008-04-20
946,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,2008-04-20
947,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,2008-04-19
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,2008-04-19
949,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,2008-04-18

### Selecting Row

In [29]:

student_data = {
    'name' : ['nitish','ankit','rishabh'],
   'iq': [100,80,10],
    'marks' :[90,70,8.8],
    'packages' :[120,100,14],\

}
students = pd.DataFrame(student_data)
students.set_index('name',inplace=True)
students

          iq  marks  packages
name
nitish   100   90.0       120
ankit     80   70.0       100
rishabh   10    8.8        14

### Selectinng rows using from a Data Frame
  . iloc - searches using index positions 

  . loc - searches using index labels

In [30]:
# single row
movies.iloc[100]

title_x                                           October (2018 film)
imdb_id                                                     tt7700730
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/October_(2018_film)
title_y                                                       October
original_title                                                October
is_adult                                                            0
year_of_release                                                  2018
runtime                                                           115
genres                                                  Drama|Romance
imdb_rating                                                       7.5
imdb_votes                                                      11125
story               Dan (Varun Dhawan) is living the life of any c...
summary             A group of interns are going through the usual...
tagline             This is not a love story. This is a story abou...
actors              Varun Dhawan|Banita Sandhu|Gitanjali Rao|Sahil...
wins_nominations                               3 wins & 9 nominations
release_date                                      13 April 2018 (USA)
Name: 100, dtype: object

In [31]:
# mulitple 
movies.iloc[0:50:5]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)
10,Amavas,tt8396186,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Amavas,Amavas,Amavas,0,2019,134,Horror|Thriller,2.8,235,Far away from the bustle of the city a young ...,The lives of a couple turn into a nightmare a...,NaN,Ali Asgar|Vivan Bhatena|Nargis Fakhri|Sachiin ...,NaN,8 February 2019 (India)
15,Badla (2019 film),tt8130968,https://upload.wikimedia.org/wikipedia/en/0/0c...,https://en.wikipedia.org/wiki/Badla_(2019_film),Badla,Badla,0,2019,118,Crime|Drama|Mystery,7.9,15499,Naina Sethi a successful entrepreneur finds he...,A dynamic young entrepreneur finds herself loc...,NaN,Amitabh Bachchan|Taapsee Pannu|Amrita Singh|An...,1 win,8 March 2019 (India)
20,Mere Pyare Prime Minister,tt8207768,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mere_Pyare_Prime...,Mere Pyare Prime Minister,Mere Pyare Prime Minister,0,2018,104,Drama,6.8,344,A story about four children living in a Mumbai...,A story about four children living in a Mumbai...,Meri Ek Arzi Sun Lo Zara,Rasika Agashe|Sonia Albizuri|Syna Anand|Adarsh...,NaN,15 March 2019 (India)
25,Gone Kesh,tt10017956,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gone_Kesh,Gone Kesh,Gone Kesh,0,2019,110,Drama,7.1,178,Enakshi is diagnosed with Alopecia where she ...,Enakshi is diagnosed with Alopecia where she ...,NaN,Deepika Amin|Kumar Kanchan Ghosh|Brijendra Kal...,9 wins,29 March 2019 (India)
30,Student of the Year 2,tt7255568,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Student_of_the_Y...,Student of the Year 2,Student of the Year 2,0,2019,146,Drama|Romance|Sport,2.5,12671,A student must face off against bullies and ov...,A student must face off against bullies and ov...,NaN,Tiger Shroff|Ananya Panday|Tara Sutaria|Aditya...,NaN,10 May 2019 (USA)
35,Khamoshi (2019 film),tt8268972,https://upload.wikimedia.org/wikipedia/en/e/ef...,https://en.wikipedia.org/wiki/Khamoshi_(2019_f...,Khamoshi,Khamoshi,0,2019,96,Horror|Thriller,3.7,153,A remake of an English movie Hush (2016) wher...,A remake of an English movie Hush (2016) wher...,NaN,Prabhu Deva|Tamannaah Bhatia|Bhoomika Chawla|,NaN,14 June 2019 (India)
40,Super 30 (film),tt7485048,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Super_30_(film),Super 30,Super 30,0,2019,154,Biography|Drama,8.2,13972,Anand Kumar a Mathematics genius from a modes...,Based on life of Patna-based mathematician Ana...,Inspired by the Life of Anand Kumar & His Stud...,Hrithik Roshan|Mrunal Thakur|Nandish Singh|Vir...,NaN,12 July 2019 (USA)
45,Chicken Curry Law,tt7189494,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chicken_Curry_Law,Chicken Curry Law,Chicken Curry Law,0,2019,127,Drama,6.0,19,Maya a foreigner who comes to India for her ca...,An ambitious and innocent girl falls prey to t...,NaN,Natalia Janoszek|Ashutosh Rana|Makrand Deshpan...,NaN,9 August 2019 (India)

In [32]:
#  fancing indexing
movies.iloc[[4,7,10,34,76]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
7,Bombairiya,tt4971258,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bombairiya,Bombairiya,Bombairiya,0,2019,104,Comedy|Crime|Drama,4.3,295,It follows the story of Meghna who gets embro...,It follows the story of Meghna who gets embro...,They didn't mean to change the world.,Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...,NaN,18 January 2019 (India)
10,Amavas,tt8396186,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Amavas,Amavas,Amavas,0,2019,134,Horror|Thriller,2.8,235,Far away from the bustle of the city a young ...,The lives of a couple turn into a nightmare a...,NaN,Ali Asgar|Vivan Bhatena|Nargis Fakhri|Sachiin ...,NaN,8 February 2019 (India)
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India)
76,Commando 3 (film),tt8983168,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Commando_3_(film),Commando 3,Commando 3,0,2019,133,Action|Thriller,5.7,2400,A mysterious man is on an impending mission to...,Commando 3 is a Hindi movie starring Vidyut Ja...,NaN,Vidyut Jammwal|Adah Sharma|Angira Dhar|Sumeet ...,NaN,NaN

In [33]:
#  loc 
students

          iq  marks  packages
name
nitish   100   90.0       120
ankit     80   70.0       100
rishabh   10    8.8        14

In [34]:
students.loc['nitish']
students.loc['nitish':'rishabh']
students.loc[['nitish','rishabh','ankit']]

          iq  marks  packages
name
nitish   100   90.0       120
rishabh   10    8.8        14
ankit     80   70.0       100

In [35]:
#  rows and  columns
# movies.iloc[rows,column]
movies.iloc[[2,6,8,15],[1,5,8]]

      imdb_id                    original_title runtime
2   tt6986710     The Accidental Prime Minister     112
6   tt5013008                     Fraud Saiyyan     109
8   tt6903440  Manikarnika: The Queen of Jhansi     148
15  tt8130968                             Badla     118

# filtering

In [36]:
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [43]:
# find all the final winners
mask = ipl['MatchNumber'] == 'Final'
new_def = ipl[mask]
new_def[['Season','WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals